kind: pipeline
type: docker
name: Test compiling

steps:
  - name: test
    image: alpine
    commands:
      - apk add git
      - apk add --update python3
      - apk add --update graphviz
      - pip3 install --upgrade pip setuptools
      - pip3 install requests
      - pip3 install rdflib
      - git clone https://github.com/fatestigma/ontology-visualization
      - python3 ./ontology-visualization/ontology_viz.py -o hogwarts.dot hogwarts.ttl


